  CREATE TABLE stories (
    id SERIAL PRIMARY KEY,
    owner VARCHAR(100) NOT NULL,
    media VARCHAR(200) NOT NULL,
    text VARCHAR(200) DEFAULT '',
    timestamp TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    expiresAt TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

