CREATE TABLE users (
    username VARCHAR(150) PRIMARY KEY,
    email VARCHAR(150) UNIQUE NOT NULL,
    password VARCHAR(150) NOT NULL,
    fullname VARCHAR(150) NOT NULL,
    bio VARCHAR(150) NOT NULL,
    profile VARCHAR(150) NOT NULL,
    following TEXT[] DEFAULT ARRAY[]::TEXT[],
    followers TEXT[] DEFAULT ARRAY[]::TEXT[],
    pending_requests TEXT[] DEFAULT ARRAY[]::TEXT[],
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);